# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Hero
  description: Home Hero section
  icon: 'cottage'
  tags: ['hero']

# Defines the structure of this component, as well as the default values
blueprint:
  title: Sempio Agency
  description: We help clients bring their ideas to life and foster growth in the digital realm.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
